version: '3.7'

services:

  filosofes:
    build: .
    command: ["python", "manage.py", "runserver_plus", "0.0.0.0:8000", "--settings=filosofes.settings.docker"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=changemeinprod
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=secret
      - DB_SERVICE=postgres
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=true
    links:
      - postgres
      - wdb
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=secret

  wdb:
    image: kozea/wdb
    ports:
        - "1984:1984"

volumes:
  postgres-data:
