# Generated by Django 2.1.3 on 2018-11-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/no_cover.jpg', upload_to='covers'),
        ),
    ]
