# Generated by Django 2.1.3 on 2018-12-01 21:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20181201_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Enter a brief description of the book', null=True),
        ),
    ]
